export const siteConfig = {
  brandName: "Wildflower Hair Co.",
  stylistName: "Kyia",
  logoUrl: "https://media.base44.com/images/public/6a5255ae151d27a36fddeb7b/ce3f36301_IMG_5258.jpg",
  tagline: "Rooted in grace. Blooming in beauty.",
  subTagline: "Your hair, but wilder.",
  bookingUrl: "https://kyiadalton.glossgenius.com/services",
  facebookUrl: "https://www.facebook.com/profile.php?id=61588159589693",
  instagramUrl: "https://www.instagram.com/_wildflower.hair.co_",
  salonName: "Hair Designs by Charlotte",
  salonAddress: "203 N 7th Ave",
  salonCity: "Durant, OK 74701",
  phone: "580-980-0808",
  salonPhone: "580-924-4789",
  email: "hello@wildflowerhairco.com",
};